### ISSUE TITLE
Documentation / API

### ISSUE THREAD

**Issue by flip111** [krakjoe/apcu#104]
Where can i find which functions APCu exposes? And possibly read about APCu some more?

**Comment by fprochazka** [comment]
http://php.net/apc

**Comment by krakjoe** [comment]
Currently it exposes an APC API if built with backward compatibility enabled, it hasn't yet got an entry of it's own in the manual, I plan to do something about that.

If anyone wants to help out, they are very welcome ...

**Comment by teo1978** [comment]
Is there ANY decent and up-to-date documentation of APCu and its currently relevant php configuration options? As opposed, I mean, to the old APC documentation, where you have to go through a lot of settings that are no longer relevant (those related to opcode cache) and quite a few that you have to figure out whether or not are relevant (because the old description is unclear and it's not trivial to tell whether or not they also apply to user cache and hence may still be useful)

**Comment by krakjoe** [comment]
I have just committed documentation for APCu ... 

It should be generally available at the end of the week (friday sometime).

If I missed anything out, anyone can make changes at http://edit.php.net

Sorry it took so long ...
