### ISSUE TITLE
apcu_entry hangs

### ISSUE THREAD

**Issue by rbro** [krakjoe/apcu#246]
I am running into an issue where calling apcu_entry hangs.  It seems to always happen on the 2nd request to apcu_entry.

The script I'm calling is:

```
<?php
apcu_entry('a', function() {});
```

I am running PHP 7.1.4 on nginx/php-fpm with apcu 5.1.8.

When I hit the above script in a browser, the 1st request returns instantly, but the 2nd request hangs.

If I restart php-fpm, I can reproduce - the 1st request runs, but the 2nd hangs.

Is there something I can do to help debug this?

Thanks for your help.

**Comment by sukhjit** [comment]
I've got the same issue too on APCU 5.1.8, try reverting back to version 5.1.7 in the meantime.

**Comment by BjornTwachtmann** [comment]
I've got the same issue as this on APCU 5.1.8 and 5.1.9 with PHP 7.1.9

This is really fundamentally broken. Multiple calls to this function hang the entire php-fpm interpreter. I was using this function in a seldom called codepath and it was causing PHP on entire servers to hang in production. 

Could this function either be fixed or temporarily removed/no-op'ed . This is a really serious bug and it bites you in ways you wouldn't necessarily expect due to not hanging the first time it's called.
