### ISSUE TITLE
apcu_cas always returns true when cache slot does not exist

### ISSUE THREAD

**Issue by user2180613** [krakjoe/apcu#309]
When a cache slot does not exist, `apcu_cas` puts a new value in the cache slot, 0. However, if `$old_value` is not 0, then `apcu_cas` will still return true, when false is expected. Also, always setting the value to 0 should not happen, in my opinion.

```
var_dump(apcu_cas("non-existing key 1", 100, 200)); // true
var_dump(apcu_fetch("non-existing key 1")); // 0

var_dump(apcu_cas("non-existing key 2", 0, 100)); // true
var_dump(apcu_fetch("non-existing key 2")); // 100
```

**Comment by nikic** [comment]
This issue has been fixed in https://github.com/krakjoe/apcu/commit/265dc875a3545d7eea4e194b70f05d903d62a4ec (as part of a non-atomicity fix for apcu_inc/dec). Additionally, https://github.com/krakjoe/apcu/commit/a720e6c6a7400bf5d4c20eec008196ecee036954 changed apcu_cas to no longer insert an entry if it did not exist. Both changes are not released yet though.

**Comment by nikic** [comment]
New apcu version with these changes has been released, so closing this issue.
