### ISSUE TITLE
Remove apcue?

### ISSUE THREAD

**Issue by nikic** [krakjoe/apcu#331]
Is this still used / relevant? The code doesn't look fully PHP 7 compatible (long vs zend_long).

/cc @krakjoe

**Comment by LionsAd** [comment]
What does that do anyway?

**Comment by nikic** [comment]
It provides an additional cache that's independent from the main one. I think it's a good idea, but the current implementation is very limited (and I think currently broken).

**Comment by LionsAd** [comment]
If we want to do that:

Would it not be better to allow to create several apc_cache* structures and just use a class like Yac() to initialize those -- they would share a common SMA though.

I see the merit for Drupal indeed:

Instead of having to prefix everything you just get your own private cache - because we have 'bins' or 'buckets' in Drupal, so an evolution of apcue could be:

```
$this->apcu = new APCuCache("bootstrap", $entries_hint = 4096); // entries_hint is ignored after first initialization.
$this->apcuStore('foo', 'bar');
$this->apcuFetch('foo');
// ...
```

Yes, we'd need another hash table to take care of apc_cache* objects, but afterwards we can transparently pass through ...

It also allows to automatically get finer grained locking -- as bins are isolated.

Caller would no longer need to do the dance to prefix APCu keys, then unprefix after fetch again ...

**Comment by nikic** [comment]
Yes, that's basically what I have in mind as well.

This also ties in with #238, which is about having separate apcu caches per fpm pool. This could be solved by making the primary apcu cache to which the free functions refer also have a name, and allow that to be specified on a per-pool basis.

Sharing one common SMA is slightly problematic wrt cache expunge. Right now if SMA runs full it triggers an expunge on the (one and only) cache. I guess it wouldn't be terrible if we expunged all caches that are associated with a given SMA instance.

**Comment by TysonAndre** [comment]
With https://github.com/krakjoe/apcu/commit/b21080e12cd31a9b4cc36a4329e4f071832dfd63 merged, this issue can be closed
