### ISSUE TITLE
Use atomic operations for apcu_inc/dec

### ISSUE THREAD

**Issue by nikic** [krakjoe/apcu#343]
This was already implemented in #334 for apcu_cas. The goal is to allow these operations to be performed under a read-lock instead of a write-lock.

A complication for apcu_inc/dec is that we'd have to switch to wraparound behavior (rather than saturating to a float). At least if we want to use straight line atomic add/sub rather than a cas loop with explicit overflow check.

**Comment by LionsAd** [comment]
I think it's too large a change for a patch release, but too less a change for a major release.

SemVer States that the contract is on the public documented API -- not on side effects.

If someone relied on the stall behavior in the past, then they can use 'cas' instead. As long as we explicitly document the change in the changelog and in the documentation:

"Since 5.2.0 inc / dec wrap around at MAX, before it would stall. Use cas if you need the old behavior"

we should be good. Technically we are creating a contract with that announcement as we then document inner bahvior, but as there is no reason to go back from atomic in the future, I am not seeing that as a problem.

**Comment by Krinkle** [comment]
Wikipedia is currently considering working around this apparent limitation in the MediaWiki core software ([change set](https://gerrit.wikimedia.org/r/#/c/mediawiki/core/+/524078/4/includes/libs/objectcache/APCUBagOStuff.php)). I'd welcome some feedback or suggestions for how to best do this currently.

Our current thinking is to use our abstraction layer to silently mock use of incr/decr with two calls: `apcu_fetch` followed by `apcu_cas`, with a retry loop around it in case of race conditions. If there's a better way you can recommend, I'd love to know :)

**Comment by nikic** [comment]
I think it may be easiest to just implement this here :)

**Comment by nikic** [comment]
I've implemented two variants at #384 and #385. The first uses a simple atomic add uses wraparound semantics. The second uses an atomic CAS loop to preserve current overflow to float.

Personally I'd be inclined to go with the simpler and more efficient wraparound variant -- IMHO this behaviour is expected as standard for atomic inc/dec operations.

**Comment by nikic** [comment]
New version 5.1.18 with the atomic implementation has been released.
