### ISSUE TITLE
Update documentation on apcu ini settings

### ISSUE THREAD

**Issue by nikic** [krakjoe/apcu#349]
http://php.net/manual/en/apcu.configuration.php seems to be mostly copied from the APC docs and a lot of things refer to the no longer existing file cache. Furthermore a number of ini settings like apc.rfc1867 no longer exist (at least in apcu 5.1.x).

**Comment by andypost** [comment]
Does it makes sense to split apc and apcu this days? I seen few times apcu_bc still used

**Comment by GeniusLe** [comment]
I think you need to provide some detailed configuration information, and I will update it.

**Comment by williamdes** [comment]
That would be nice to remove that from the documentation, I was thinking that `apc.rfc1867` was still working

**Comment by nikic** [comment]
@williamdes These have already been removed quite a while ago in https://github.com/php/doc-en/commit/7ff4c27858f8cf53ca34a4c552ec4dcc09e2ab2b. Which documentation are you looking at?

**Comment by williamdes** [comment]
> @williamdes These have already been removed quite a while ago in [php/doc-en@7ff4c27](https://github.com/php/doc-en/commit/7ff4c27858f8cf53ca34a4c552ec4dcc09e2ab2b). Which documentation are you looking at?

Thank you for your kind response, it is in https://github.com/krakjoe/apcu/blob/b68953ccbc1a5234c2caf8ed5800afd222270948/INSTALL#L292

Because it is still shipped with the extension I still had some hope

Could you give me an official confirmation that apcu has no way to provide upload progress so I can remove the code from phpMyAdmin?
And the two only methods are uploadprogress from pecl and session upload progress

(sorry if that falls a bit off topic)

**Comment by nikic** [comment]
@williamdes I've deleted that INSTALL file in https://github.com/krakjoe/apcu/commit/c2ca04f5b42541d88a6836d6fd5553ab756eb87b, it was pretty outdated. And yes, there is no upload progress support in apcu.

Also going to close this issue, as I think it's been mostly addressed in the meantime...

**Comment by LionsAd** [comment]
@williamdes Also really off-topic, but: Why don’t you use a JS based upload progress method like dropzoneJS or many others instead of relying on the server capabilities?

**Comment by williamdes** [comment]
> @williamdes Also really off-topic, but: Why don’t you use a JS based upload progress method like dropzoneJS or many others instead of relying on the server capabilities?
> 
> (huge fan of PHPMyAdmin hence wanting to give feedback - sorry for the noise Niki)

This is a very good question I also asked myself, maybe we should use some JS lib. I did a quick search some days ago and I think that http://www.resumablejs.com/ is a better choice, the actual PHP code is old and not maintained but since I re-wrote some of it that could be a solution: https://github.com/code-lts/resumable.php

> huge fan of PHPMyAdmin hence wanting to give feedback

yay !

I think the conclusion is that old code needs to be replaced but keeping in mind all the previous upload methods still have to work, etc.. 😸
