### ISSUE TITLE
APCu crashing on IIS 7.5

### ISSUE THREAD

**Issue by flip111** [krakjoe/apcu#67]
IIS version: 7.5.7600.16385
APC version: 4.0.3 5.5 Non Thread Safe (NTS) x86 http://pecl.php.net/package/APCu/4.0.3/windows
PHP version: 5.5.9

Error:
```
Faulting application name: php-cgi.exe, version: 5.5.9.0, time stamp: 0x52f2a88e
Faulting module name: php_apcu.dll, version: 5.5.4.0, time stamp: 0x52eb73db
Exception code: 0xc0000005
Fault offset: 0x000030fa
Faulting process id: 0x1aa0
Faulting application start time: 0x01cf32225008c0f4
Faulting application path: C:\PHP\php-cgi.exe
Faulting module path: C:\PHP\ext\php_apcu.dll
Report Id: 8e489ac4-9e15-11e3-8480-8c89a5711264
```

INI
```
[APCu]
extension=php_apcu.dll
apc.enabled=1
```
(no additional settings to APCu were set)

Opcache settings (might be related ??)
```
[opcache]
zend_extension = C:\PHP\ext\php_opcache.dll
opcache.enable=1
opcache.memory_consumption=256
opcache.interned_strings_buffer=16
opcache.max_accelerated_files=16000
opcache.enable_file_override=1
opcache.error_log = C:\inetpub\php_logs\php_opcache_prod.log
opcache.log_verbosity_level=2
```

**Comment by yurii-github** [comment]
setting to 1 instance worked for me on IIS-FastCGI

**Comment by fedevegili** [comment]
After lots of debugging, I found out that I'm having this very same issue. If I set more than one instance for IIS FastCgi and do some heavy loading, boom, it crashes.

If you guys need, I can provide some really simple testing example (5 lines of code) and even a set up VM.

Is there any updates about this issue? Unfortunately, we'll have to look for another solution for now because we can't lower our fastcgi instantes. :(

**Comment by krakjoe** [comment]
If it really is the case that the locks we are using on windows are not suitable for sharing among processes (the ones we use on elsewhere are), that's pretty terrible. Isn't there a more suitable lock @weltling ?

I don't know anything about windows ...

**Comment by krakjoe** [comment]
Please try with the latest release on pecl, and report back ?

**Comment by nicolas-grekas** [comment]
I don't know if it's related to the issue reported here, but 4.0.8 still segfaults on the Symfony test suite:
https://ci.appveyor.com/project/nicolas-grekas/symfony/build/1.0.8#L1164
Sorry I don't have a better report to give...

**Comment by krakjoe** [comment]
Can you try with 4.0.10 or 5.1.2 please ?

**Comment by weltling** [comment]
May i also ask to check the builds here http://windows.php.net/downloads/pecl/snaps/apcu/5.1.2_global_mutex/ and the branch they're made from https://github.com/krakjoe/apcu/tree/win_global_mutex ? 

Those are experimental so not expected to be perfect. Though i see some improvement in the multi-process environment. Thread safe SAPIs like Apache might be hit by some slowdown as mutexes are per se slower, here they're even global. On the other hand, as example, thread safe FCGI bins could be perfectly used if one would want to utilize pthreads extension.

So except we decide to determine we're under a real TS SAPI, a universal locking could make sense and simplify.

Thanks.

**Comment by samdark** [comment]
4.0.10 crashes at `apc_cache_insert(_apc_cache_t *, apc_cache_key_t, apc_cache_entry_t *, _apc_context_t *, long, unsigned char)` as well with:

```
Unhandled exception at 0x5D0A311A (php_apcu.dll) in php-cgi.exe: 0xC0000005: Access violation reading location 0x00000004.
```

**Comment by samdark** [comment]
@weltling tried mutex branch with PHP 7 ts. Crashes at `apc_cache_fetch(_apc_cache_t *, _zend_string *, long, _zval_struct * *)` with:

```
Unhandled exception at 0x0E1C2527 (php_apcu.dll) in php-cgi.exe: 0xC0000005: Access violation reading location 0x15115A28.
```

**Comment by weltling** [comment]
@samdark thanks for checking. Were some more info possible, some code and the way you run it? In my checks i was oriented on the repro case posted earlier by @JEDIBC https://github.com/krakjoe/apcu/issues/67#issuecomment-60909587

Thanks.

**Comment by krakjoe** [comment]
Also, those trace lines look like 32 bit, is that the case ?? 

Architecture might be significant somehow ...

**Comment by samdark** [comment]
@krakjoe yes, these are 32bit.

**Comment by samdark** [comment]
@weltling happend when I'm doing writes/reads in PHP scripts that are called at the same time via AJAX.  I'm using [this little thing](https://github.com/deemru/php-cgi-spawner) to spawn 4 cgi processes and nginx with 4 workers to serve them.

**Comment by krakjoe** [comment]
So, it turns out that the processing model used by IIS is simply incompatible with the way APC(u) shares memory and uses locking.

@weltling has suggested that he may try to lift the limitation for Windows. In my opinion it's not even worth pursuing for non-windows operating systems, so, I'm going to mark the bug closed, though that's not necessarily the end of the conversation ;)

**Comment by flip111** [comment]
I would suggest actively notifying the user about this. Throwing errors/warnings when on the windows platform and explicitly mention it in the documentation.

**Comment by samdark** [comment]
It's not IIS only. My crashes are when running multiple cgi processes.

**Comment by weltling** [comment]
@samdark i confirm the crashes you've reported. It's not about IIS particularly, it's about the post fork model. It is the only model possible on Windows for a multi-process usage. Unfortunately, it is not possible to use APC and consequently APCu with this model. But, APCu can still be used flawlessly with Apache on Windows.

Today, either pre fork on TS SAPI scenario is only usable on any platform. Both Joe and me believed the crash issues were solvable with some stronger locking, but after a deep investigation it turns out it's not the case. The shared memory model in ext/apc that is inherited by ext/apcu won't allow starting separate processes sharing the same memory on any platform, which is now uncovered with the case of FCGI. It is not a big issue on Linux as multiple FCGI fcgi processes can be started using fork(), but it's for sure a blocking issue for using APCu with FCGI on Windows. A fix will require some quite hard refactoring not for the locking, but for the shared memory model. I could still go for such refactoring, if there are lots of users vouching this thus giving be the reason to plan my times.

Btw the spawner prog you've linked is a very interentisting approach. I think some similar should be integrated with the next PHP versions. That will finally allow to separate FCGI and actual web server hosts.

Thanks.

Anatol

**Comment by samdark** [comment]
To me it's nice to have but not critical. Should be documented though as, I think, it's relatively common.

**Comment by tomolimo** [comment]
See https://github.com/krakjoe/apcu-bc/issues/17 where I described the same issue

**Comment by pierre-H** [comment]
I have the same problem with nginx.
@samdark did you find a solution ? Thanks !

**Comment by samdark** [comment]
I've personally never experienced it with nginx and on Windows I'm using php-cgi-spawner: https://github.com/samdark/wnmp-dev

**Comment by siburny** [comment]
I recently added second IIS site with FCGI PHP handler. I set "Max Instances" to 1 hoping it would work as well, but it didn't. Each IIS site uses it's own php-cgi.exe process so first process to start grabs the shared memory block. Others throw an error like this:
```
[06-Nov-2018 21:45:06 America/New_York] PHP Fatal error:  PHP Startup: apc_shm_create: shmget(0, 1048576, 658) failed: No such file or directory. It is possible that the chosen SHM segment size is higher than the operation system allows. Linux has usually a default limit of 32MB per segment. in Unknown on line 0
[06-Nov-2018 21:45:06 America/New_York] PHP Fatal error:  PHP Startup: apc_shm_attach: shmat failed: in Unknown on line 0
```

**Comment by ifew** [comment]
I got same errors, but set "Max Instances" to "1" is work for me
