### ISSUE TITLE
apcu + "request_terminate_timeout" in php-fpm.conf cause deadlock

### ISSUE THREAD

**Issue by fadimko** [krakjoe/apcu#86]
If php-fpm kills it's worker process in the middle of apcu operation, then the process will never release the mutex and php-fpm freezes. In linux the problem can be solved with [robust mutexes](http://pubs.opengroup.org/onlinepubs/9699919799/functions/pthread_mutexattr_getrobust.html).

upd: No, it can not. https://bugs.php.net/bug.php?id=69048

**Comment by fadimko** [comment]
up

**Comment by krakjoe** [comment]
So, I'm going to say that this isn't reasonably fixable.

The idea of using lock free storage is scary, there is already such an extension written by Xinchen. The whole idea is mostly untested, while rather clever ... The problem is stampede would be extreme; If nothing locks, then everyone does everything for a cold cache.

I'm going to say that the solution is don't use request terminate timeout if you are using APC/APCu/Opcache/or any other cache or thing that is extremely sensitive to deadlocking.

**Comment by xiezhenye** [comment]
What about use pthread_mutexattr_setrobust and raise an error when lock returns EOWNERDEAD?



 @krakjoe
